# /// script
# dependencies = ["nkeys"]
# ///
"""Writes jwt.conf and user.creds. Run from erlang/: uv run test/fixtures/make_jwt.py"""
import base64, binascii, hashlib, json, nkeys

def b32(b): return base64.b32encode(b).decode().rstrip("=")
def seed_for(prefix_byte, raw):
    body = bytes([(18 << 3) | (prefix_byte >> 5), (prefix_byte & 31) << 3]) + raw
    return b32(body + binascii.crc_hqx(body, 0).to_bytes(2, "little"))
def kp(seed): return nkeys.from_seed(seed.encode())
def b64(b): return base64.urlsafe_b64encode(b).decode().rstrip("=")

def jwt(issuer, sub, name, nats):
    claims = {"iat": 1700000000, "iss": issuer.public_key.decode(), "name": name,
              "sub": sub, "nats": nats}
    claims["jti"] = b32(hashlib.sha256(json.dumps(claims, sort_keys=True).encode()).digest())
    head = b64(json.dumps({"typ": "JWT", "alg": "ed25519-nkey"}).encode())
    body = b64(json.dumps(claims).encode())
    return head + "." + body + "." + b64(issuer.sign((head + "." + body).encode()))

operator = kp(seed_for(14 << 3, bytes(range(32))))
account = kp(seed_for(0, bytes(range(32, 64))))
system = kp(seed_for(0, bytes(range(64, 96))))
user_seed = "SUACSSL3UAHUDXKFSNVUZRF5UHPMWZ6BFDTJ7M6USDXIEDNPPQYYYCU3VY"
user = kp(user_seed)
op_pub, acc_pub = operator.public_key.decode(), account.public_key.decode()
sys_pub = system.public_key.decode()

op_jwt = jwt(operator, op_pub, "op", {"type": "operator", "version": 2, "system_account": sys_pub})
limits = {"subs": -1, "data": -1, "payload": -1, "imports": -1, "exports": -1,
          "wildcards": True, "conn": -1, "leaf": -1}
acc_jwt = jwt(operator, acc_pub, "acc", {"limits": limits, "type": "account", "version": 2})
sys_jwt = jwt(operator, sys_pub, "SYS", {"limits": limits, "type": "account", "version": 2})
user_jwt = jwt(account, user.public_key.decode(), "user",
               {"pub": {}, "sub": {}, "subs": -1, "data": -1, "payload": -1,
                "type": "user", "version": 2})

open("test/fixtures/jwt.conf", "w").write(
    "# Generated by test/fixtures/make_jwt.py.\n"
    f"operator: {op_jwt}\nsystem_account: {sys_pub}\nresolver: MEMORY\n"
    f"resolver_preload: {{\n  {acc_pub}: {acc_jwt}\n  {sys_pub}: {sys_jwt}\n}}\n")
open("test/fixtures/user.creds", "w").write(
    f"-----BEGIN NATS USER JWT-----\n{user_jwt}\n------END NATS USER JWT------\n\n"
    "************************* IMPORTANT *************************\n"
    "NKEY Seed printed below can be used to sign and prove identity.\n"
    "NKEYs are sensitive and should be treated as secrets.\n\n"
    f"-----BEGIN USER NKEY SEED-----\n{user_seed}\n------END USER NKEY SEED------\n\n"
    "*************************************************************\n")
print(op_pub, acc_pub)
